"""Read-model contract for administrator analytics."""
from __future__ import annotations

from typing import Any, Dict, List, Protocol


class AnalyticsRepository(Protocol):
    def user_overview(self, user_id: str) -> Dict[str, Any]: ...
    def global_user_stats(self) -> Dict[str, Any]: ...
    def global_task_stats(self) -> Dict[str, Any]: ...
    def global_attribute_stats(self) -> Dict[str, Any]: ...
    def global_growth_point_stats(self) -> Dict[str, Any]: ...
    def global_document_stats(self) -> Dict[str, Any]: ...
    def user_registration_trend(self, days: int) -> List[Dict[str, Any]]: ...
    def user_activity_stats(self, days: int) -> Dict[str, Any]: ...
    def user_level_distribution(self) -> List[Dict[str, Any]]: ...
    def task_status_distribution(self) -> List[Dict[str, Any]]: ...
    def task_completion_trend(self, days: int) -> List[Dict[str, Any]]: ...
    def task_category_stats(self) -> List[Dict[str, Any]]: ...
    def task_duration_stats(self) -> Dict[str, Any]: ...
    def attribute_type_distribution(self) -> List[Dict[str, Any]]: ...
    def attribute_value_distribution(self) -> List[Dict[str, Any]]: ...
    def popular_attributes(self, limit: int) -> List[Dict[str, Any]]: ...
    def growth_point_activity_trend(self, days: int) -> List[Dict[str, Any]]: ...
    def growth_point_distribution(self) -> List[Dict[str, Any]]: ...
    def growth_point_health_metrics(self) -> Dict[str, Any]: ...
