"""Contracts for user-owned conversation persistence."""
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Protocol


@dataclass(frozen=True)
class ConversationError(Exception):
    code: str
    message: str
    status_code: int = 400

    def __str__(self) -> str:
        return self.message


class ConversationRepository(Protocol):
    def list_groups(self, user_id: str) -> List[Dict[str, Any]]: ...
    def create_group(self, user_id: str, name: str) -> str: ...
    def update_group(self, user_id: str, group_id: str, name: str) -> bool: ...
    def delete_group(self, user_id: str, group_id: str) -> bool: ...
    def create_session(self, user_id: str, group_id: str, name: str, session_id: Optional[str] = None) -> Optional[str]: ...
    def update_session(self, user_id: str, session_id: str, name: Optional[str], group_id: Optional[str]) -> bool: ...
    def delete_session(self, user_id: str, session_id: str) -> bool: ...
    def duplicate_session(self, user_id: str, session_id: str) -> Optional[str]: ...
    def list_messages(self, user_id: str, session_id: str, limit: int) -> Optional[List[Dict[str, Any]]]: ...
    def add_message(self, user_id: str, session_id: str, role: str, content: str, tokens: int, reply_to_id: Optional[str]) -> Optional[str]: ...
    def clear_messages(self, user_id: str, session_id: str) -> bool: ...
