"""Contracts for a user's capabilities and reward economy."""
from __future__ import annotations

from typing import Any, Dict, List, Mapping, Optional, Protocol


class GrowthProfileError(Exception):
    """Expected growth profile failures for transport adapters to translate."""

    def __init__(self, message: str, code: str, status_code: int = 400) -> None:
        super().__init__(message)
        self.message = message
        self.code = code
        self.status_code = status_code


class GrowthProfileRepository(Protocol):
    def get_balance(self, user_id: str) -> int: ...
    def list_resources(self, user_id: str) -> Dict[str, int]: ...
    def list_coin_history(self, user_id: str, limit: int) -> List[Dict[str, Any]]: ...
    def income_expense_stats(self, user_id: str) -> Dict[str, Any]: ...
    def list_attributes(self, user_id: str) -> List[Dict[str, Any]]: ...
    def get_attribute(self, user_id: str, attr_id: str) -> Optional[Dict[str, Any]]: ...
    def create_attribute(self, user_id: str, values: Mapping[str, Any]) -> str: ...
    def update_attribute(self, user_id: str, attr_id: str, values: Mapping[str, Any]) -> bool: ...
    def delete_attribute(self, user_id: str, attr_id: str) -> bool: ...
