"""Contracts for temporary attachment sessions."""
from __future__ import annotations

from typing import Any, Dict, Protocol


class SessionAttachmentError(Exception):
    def __init__(self, message: str, code: str, status_code: int = 400) -> None:
        super().__init__(message)
        self.message = message
        self.code = code
        self.status_code = status_code


class SessionAttachmentGateway(Protocol):
    def owns_session(self, user_id: str, session_id: str) -> bool: ...
    def create_session(self, user_id: str) -> Dict[str, Any]: ...
    def upload(self, user_id: str, session_id: str, file_data: bytes, file_name: str) -> Dict[str, Any]: ...
    def context(self, user_id: str, session_id: str) -> Dict[str, Any]: ...
    def active_sessions(self, user_id: str) -> Dict[str, Any]: ...
    def file_content(self, user_id: str, file_id: str) -> Dict[str, Any]: ...
    def image_data_url(self, user_id: str, session_id: str, file_id: str) -> str | None: ...
    def delete_file(self, user_id: str, file_id: str) -> Dict[str, Any]: ...
