"""Portable contracts for Trigger-to-Run automation."""
from __future__ import annotations

from typing import Any, Dict, Mapping, Optional, Protocol, Sequence


class TaskAutomationError(Exception):
    def __init__(self, message: str, code: str, status_code: int = 400) -> None:
        super().__init__(message)
        self.message = message
        self.code = code
        self.status_code = status_code


class TaskAutomationRepository(Protocol):
    def create_trigger(self, user_id: str, values: Mapping[str, Any]) -> Dict[str, Any]: ...
    def list_triggers(self, user_id: str) -> Sequence[Dict[str, Any]]: ...
    def get_trigger(self, user_id: str, trigger_id: str) -> Optional[Dict[str, Any]]: ...
    def update_trigger(self, user_id: str, trigger_id: str, values: Mapping[str, Any]) -> bool: ...
    def delete_trigger(self, user_id: str, trigger_id: str) -> bool: ...
    def set_trigger_status(self, user_id: str, trigger_id: str, status: str) -> bool: ...
    def get_firing(self, user_id: str, trigger_id: str, source_key: str) -> Optional[Dict[str, Any]]: ...
    def record_firing(self, user_id: str, trigger_id: str, source_key: str, run_id: str, payload: Mapping[str, Any]) -> Dict[str, Any]: ...
